apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpu-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpu-api
  template:
    metadata:
      labels:
        app: gpu-api
    spec:
      containers:
      - name: gpu-api
        image: gpu-test-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          limits:
            nvidia.com/gpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gpu-api
spec:
  selector:
    app: gpu-api
  ports:
  - port: 8000
    targetPort: 8000
  type: NodePort
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: gpu-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gpu-api
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Object
    object:
      metric:
        name: DCGM_FI_DEV_GPU_UTIL_AVG
      describedObject:
        kind: Service
        name: gpu-api
      target:
        type: Value
        value: '30'
